/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestSo */

#ifndef _Included_TestSo
#define _Included_TestSo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestSo
 * Method:    setCallBack
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TestSo_setCallBack
  (JNIEnv *, jobject);

/*
 * Class:     TestSo
 * Method:    checkpoint
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_TestSo_checkpoint
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
