/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xdev_niodev_NIODevice */

#ifndef _Included_xdev_niodev_NIODevice
#define _Included_xdev_niodev_NIODevice
#ifdef __cplusplus
extern "C" {
#endif
#undef xdev_niodev_NIODevice_ACK_HEADER
#define xdev_niodev_NIODevice_ACK_HEADER -23L
#undef xdev_niodev_NIODevice_SHUTDOWN_SIGNAL
#define xdev_niodev_NIODevice_SHUTDOWN_SIGNAL -13L
#undef xdev_niodev_NIODevice_END_OF_STREAM
#define xdev_niodev_NIODevice_END_OF_STREAM -14L
/*
 * Class:     xdev_niodev_NIODevice
 * Method:    setCallBack
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xdev_niodev_NIODevice_setCallBack
  (JNIEnv *, jobject, jstring);

/*
 * Class:     xdev_niodev_NIODevice
 * Method:    checkpoint
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_xdev_niodev_NIODevice_checkpoint
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
